platform :ios, :deployment_target => "5.0"
  pod 'ObjectiveSugar'
  pod 'ObjectiveRecord', :local => '../ObjectiveRecord.podspec'
target :test, :exclusive => true do
  link_with 'SampleProjectTests'
  pod 'Kiwi'
end
